server:
  port: 9999
spring:
  datasource:
    url: jdbc:goldilocks://localhost:2581/goldilocks
    driver-class-name: sunje.goldilocks.jdbc.GoldilocksDriver
    username: lms
    password: lms
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.csii.demo.entity